name: Creating miultistage docker image

on: 
  push:
    branches: ["*"]
  pull_request: 
    branches: ["*"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: echo "${{ secrets.TOKEN }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin
      
      - name: Build Dockerfile image for amd64
        run: docker build --platform=linux/amd64 -t al3xus22/programlab5:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker build --platform=linux/arm64 -t al3xus22/programlab5:arm64 --push .
      
      - name: Create manifest
        run: docker manifest create al3xus22/programlab5 --amend al3xus22/programlab5:amd64 --amend al3xus22/programlab5:arm64

      - name: Push manifest to dockerHub
        run: docker manifest push al3xus22/programlab5

