name: Build Debian Package

on:
  push:
    branches:
      - branchAutoPackage
  pull_request:
    branches:
      - branchAutoPackage

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Make debian/rules executable
      run: chmod +x debian/rules

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper-compat dh-make

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc

    - name: Upload .deb package
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: "./*.deb"
